/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//CUSTOMER MANAGEMENT COMPLETE

package GUI;
import Classes.Customer;
import Files.CustomerFileIO;
import Files.PackageFileIO;
import javax.swing.JOptionPane;

import javax.swing.JFrame;
//import javax.swing.JLabel;

/**
 *
 * @author Miko
 */
public class CustMgmtJFrame extends javax.swing.JFrame {
    CustomerFileIO custObj = new CustomerFileIO();
    PackageFileIO packObj = new PackageFileIO();
    
    
    int IC,pNo;
    String name,sName,sAdd;
    
    private void clearField(){
        this.txtIC.setText("");
        this.txtIC2.setText("");
        this.txtName.setText("");
        this.txtName2.setText("");
        this.txtSAdd.setText("");
        this.txtSAdd2.setText("");
        this.txtSName.setText("");
        this.txtSName2.setText("");
        this.txtMax.setText("");
        this.txtMax2.setText("");
        this.txtMin.setText("");
        this.txtMin2.setText("");
        this.txtRate.setText("");
        this.txtRate2.setText("");              
    }
    
    /**
     * Creates new form CustMgmtJFrame
     */
    public CustMgmtJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerHeader3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        lblCustomerHeader1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtIC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSAdd = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cBoxPackageNo = new javax.swing.JComboBox();
        txtRate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblCustomerHeader2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtIC2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSName2 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtSAdd2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cBoxPackageNo2 = new javax.swing.JComboBox();
        txtRate2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnSave2 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtMax2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtMin2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerHeader3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCustomerHeader3.setText("Delivery Management System(DMS)");

        lblCustomerHeader1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCustomerHeader1.setText("Add New Customer");

        jLabel18.setText("Name : ");

        jLabel19.setText("IC : ");

        jLabel20.setText("Shipper Name : ");

        txtSAdd.setColumns(20);
        txtSAdd.setRows(5);
        jScrollPane8.setViewportView(txtSAdd);

        jLabel21.setText("Shipper Address : ");

        jLabel22.setText("Package : ");

        cBoxPackageNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cBoxPackageNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPackageNoActionPerformed(evt);
            }
        });

        txtRate.setEnabled(false);
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });

        jLabel23.setText("Rate : ");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel31.setText("Max:");

        txtMax.setEnabled(false);
        txtMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxActionPerformed(evt);
            }
        });

        txtMin.setEnabled(false);
        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });

        jLabel32.setText("Min:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cBoxPackageNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCustomerHeader1))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblCustomerHeader1)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtIC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cBoxPackageNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Customer", jPanel6);

        lblCustomerHeader2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCustomerHeader2.setText("Edit Customer Record");

        jLabel25.setText("Name : ");

        txtName2.setEnabled(false);

        jLabel26.setText("IC : ");

        jLabel27.setText("Shipper Name : ");

        txtSName2.setEnabled(false);

        txtSAdd2.setColumns(20);
        txtSAdd2.setRows(5);
        txtSAdd2.setEnabled(false);
        jScrollPane9.setViewportView(txtSAdd2);

        jLabel28.setText("Shipper Address : ");

        jLabel29.setText("Package : ");

        cBoxPackageNo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cBoxPackageNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPackageNo2ActionPerformed(evt);
            }
        });

        txtRate2.setEnabled(false);
        txtRate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRate2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Rate : ");

        btnSave2.setText("Save");
        btnSave2.setEnabled(false);
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel33.setText("Max:");

        txtMax2.setEnabled(false);
        txtMax2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMax2ActionPerformed(evt);
            }
        });

        jLabel34.setText("Min:");

        txtMin2.setEnabled(false);
        txtMin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxPackageNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSName2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRate2)
                                    .addComponent(btnSave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblCustomerHeader2))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblCustomerHeader2)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cBoxPackageNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtMax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addComponent(btnSave2)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Customer Record", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCustomerHeader3)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblCustomerHeader3)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void txtRate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRate2ActionPerformed

    private void txtMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    private void txtMax2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMax2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMax2ActionPerformed

    private void txtMin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMin2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //CHANGES DONE IC set as UNIQUE Key 
        boolean nameCheck=false;
        int tempIC;
        try {
            IC=Integer.parseInt(this.txtIC.getText());
            pNo=Integer.parseInt(this.cBoxPackageNo.getSelectedItem().toString());
            name=this.txtName.getText();
            sName=this.txtSName.getText();
            sAdd=this.txtSAdd.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Input Format", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        custObj.retrieveData();
        for (int i = 0; i < custObj.custV.size(); i++) {
            tempIC=custObj.custV.elementAt(i).getCustIC();
            if (tempIC==IC) {
                nameCheck=true;
                break;
            }
        }
        
        if (nameCheck) {
            JOptionPane.showMessageDialog(this, "IC number existing", "Duplicate IC",
                    JOptionPane.ERROR_MESSAGE);
        }
        else {
            Customer customer = new Customer(IC,name,sName,sAdd,pNo);
            custObj.add(customer);
            JOptionPane.showMessageDialog(this, "Customer Successful Added!", "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            clearField();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cBoxPackageNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPackageNoActionPerformed
        //CHANGES DONE AutoPassing cBoxPackageNo, if cBoxPackageNo == 0 ,then empty package detail
        if (this.cBoxPackageNo.getSelectedIndex()==0) {
            this.txtRate.setText("");
            this.txtMax.setText("");
            this.txtMin.setText("");
        }
        else {
            String No=this.cBoxPackageNo.getSelectedItem().toString();
        
            //display all record according to packageNo
            for (int i = 0; i < packObj.packV.size(); i++) {
                String tempNo = Integer.toString(packObj.packV.elementAt(i).getPackageNo());
                if (tempNo.equals(No)) {
                    this.txtMax.setText(Integer.toString(packObj.packV.elementAt(i).getMax()));
                    this.txtMin.setText(Integer.toString(packObj.packV.elementAt(i).getMin()));
                    this.txtRate.setText(Double.toString(packObj.packV.elementAt(i).getRate()));
                    break;
                }
            }
        }
        
    }//GEN-LAST:event_cBoxPackageNoActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
         try {
             
            IC=Integer.parseInt(this.txtIC2.getText());
            pNo=Integer.parseInt(this.cBoxPackageNo2.getSelectedItem().toString());
            name=this.txtName2.getText();
            sName=this.txtSName2.getText();
            sAdd=this.txtSAdd2.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Input", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Customer customer = new Customer(IC,name,sName,sAdd,pNo);
        custObj.edit(customer); 
        JOptionPane.showMessageDialog(this, "Customer Record Successful Edited!", "Information",JOptionPane.INFORMATION_MESSAGE);
   
        
        
//        this.cBoxPackageNo2.addItem("-");
//        for (int i = 0; i < this.cBoxPackageNo2.getItemCount(); i++) {
//            this.cBoxPackageNo2.removeItemAt(0);
//            
//        }
        clearField();
        this.btnSave2.setEnabled(false); 
        this.txtName2.setEnabled(false);
        this.txtSAdd2.setEnabled(false);
        this.txtSName2.setEnabled(false);
        
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void cBoxPackageNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPackageNo2ActionPerformed
        if (this.cBoxPackageNo2.getSelectedIndex()==0) {
            this.txtRate2.setText("");
            this.txtMax2.setText("");
            this.txtMin2.setText("");
        }
        else {
            String No=this.cBoxPackageNo2.getSelectedItem().toString();
        
            //display all record according to packageNo
            for (int i = 0; i < packObj.packV.size(); i++) {
                String tempNo = Integer.toString(packObj.packV.elementAt(i).getPackageNo());
                if (tempNo.equals(No)) {
                    this.txtMax2.setText(Integer.toString(packObj.packV.elementAt(i).getMax()));
                    this.txtMin2.setText(Integer.toString(packObj.packV.elementAt(i).getMin()));
                    this.txtRate2.setText(Double.toString(packObj.packV.elementAt(i).getRate()));
                    break;
                }
            }
        } 
    }//GEN-LAST:event_cBoxPackageNo2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        boolean recordCheck=false;
        String listCIC;
        custObj.retrieveData();
        for (int i = 0; i < custObj.custV.size(); i++) {
             listCIC=Integer.toString(custObj.custV.elementAt(i).getCustIC());
             if (listCIC.equals(this.txtIC2.getText())) {
                this.txtName2.setText(custObj.custV.elementAt(i).getCustName());
                this.txtSName2.setText(custObj.custV.elementAt(i).getShipperName());
                this.txtSAdd2.setText(custObj.custV.elementAt(i).getShipperAdd());
                System.out.println(custObj.custV.elementAt(i).PackageObj.getPackageNo());
                this.cBoxPackageNo2.setSelectedItem(custObj.custV.elementAt(i).PackageObj.getPackageNo());
                this.txtName2.setEnabled(true);
                this.txtSAdd2.setEnabled(true);
                this.txtSName2.setEnabled(true);
                recordCheck=true;
                break;
            }
        } 
            if (recordCheck) {
                
                this.btnSave2.setEnabled(true);
            }else {
                clearField();
                this.btnSave2.setEnabled(false);
                this.txtName2.setEnabled(false);
                this.txtSAdd2.setEnabled(false);
                this.txtSName2.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Record Not Found!", "Information",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustMgmtJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSearch;
    public static javax.swing.JComboBox cBoxPackageNo;
    public static javax.swing.JComboBox cBoxPackageNo2;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCustomerHeader1;
    private javax.swing.JLabel lblCustomerHeader2;
    private javax.swing.JLabel lblCustomerHeader3;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtIC2;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMax2;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtMin2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtRate2;
    private javax.swing.JTextArea txtSAdd;
    private javax.swing.JTextArea txtSAdd2;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSName2;
    // End of variables declaration//GEN-END:variables
}
