/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Classes.Order;
import Files.OrderFileIO;
import Files.PaymentFileIO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miko
 */
public class DeliveryMgmtJFrame extends javax.swing.JFrame {
    OrderFileIO orderObj = new OrderFileIO();
    PaymentFileIO payObj = new PaymentFileIO();
    /**
     * Creates new form DeliveryMgmtJFrame
     */
    public DeliveryMgmtJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerHeader3 = new javax.swing.JLabel();
        lblDeliveryHeader = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnDSearch = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cBoxDeliverStatus = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliver = new javax.swing.JTable(){

            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerHeader3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCustomerHeader3.setText("Delivery Management System(DMS)");

        lblDeliveryHeader.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblDeliveryHeader.setText("Order Delivery Management");

        jLabel16.setText("IC : ");

        btnDSearch.setText("Search");
        btnDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSearchActionPerformed(evt);
            }
        });

        jLabel17.setText("Delivery Status : ");

        cBoxDeliverStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delivered", "On-Hold " }));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblDeliver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Order No", "Status", "Customer IC", "Customer Name", "Shipping Name", "Shipping Address"
            }
        ));
        jScrollPane1.setViewportView(tblDeliver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCustomerHeader3)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDeliveryHeader)
                        .addGap(265, 265, 265))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(cBoxDeliverStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustomerHeader3)
                .addGap(35, 35, 35)
                .addComponent(lblDeliveryHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnDSearch)
                    .addComponent(jLabel17)
                    .addComponent(btnUpdate)
                    .addComponent(cBoxDeliverStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSearchActionPerformed

    }//GEN-LAST:event_btnDSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        double amount,weight;
        long IC;
        String sName,sAdd,cName,cAdd,name,oStatus,dStatus;
        
        orderObj.retrieveData();
        int index = this.tblDeliver.getSelectedRow();
        int orderNo = Integer.parseInt((this.tblDeliver.getValueAt(index, 0)).toString());
               
        dStatus = this.cBoxDeliverStatus.getSelectedItem().toString();
        this.tblDeliver.setValueAt(dStatus, index, 1);
        
        for (int i = 0; i < orderObj.orderV.size(); i++) {
            if (orderObj.orderV.elementAt(i).getorderNo()== orderNo){
                amount= orderObj.orderV.elementAt(i).getamount();
                IC=orderObj.orderV.elementAt(i).custObj.getcustIC();
                weight= orderObj.orderV.elementAt(i).getweight();
                name=orderObj.orderV.elementAt(i).custObj.getcustName();
                sName=orderObj.orderV.elementAt(i).custObj.getshipperName();
                sAdd=orderObj.orderV.elementAt(i).custObj.getshipperAdd();
                cName=orderObj.orderV.elementAt(i).getcName();
                cAdd=orderObj.orderV.elementAt(i).getcAdd();
                oStatus = orderObj.orderV.elementAt(i).getoStatus();
                Order order = new Order(amount,IC,orderNo,weight,name,sName,sAdd,cName,cAdd,oStatus,dStatus);
                orderObj.edit(order);
            }
        }        
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryMgmtJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryMgmtJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cBoxDeliverStatus;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerHeader3;
    private javax.swing.JLabel lblDeliveryHeader;
    public static javax.swing.JTable tblDeliver;
    private javax.swing.JTextField txtIC;
    // End of variables declaration//GEN-END:variables
}
