/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Classes.Order;
import Files.OrderFileIO;
import Files.CustomerFileIO;
import Files.PackageFileIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Miko
 */
public class OrderMgmtjFrame extends javax.swing.JFrame {
    OrderFileIO orderObj = new OrderFileIO();
    CustomerFileIO custObjs = new CustomerFileIO();
    PackageFileIO packObj = new PackageFileIO();
    
    double amount,weight,rate;
    int pno,IC,orderNo;
    String sName,sAdd,name,cName,cAdd;
    
    private void autoGenerator(){
        String newPno;
        
        orderObj.retrieveData();
        if(orderObj.orderV.size()==0){
            this.txtOrderNo.setText("111");
        }
        else {
           newPno=Integer.toString((orderObj.orderV.lastElement().getOrderNo())+1);
           this.txtOrderNo.setText(newPno.toString());
        }
    }
    
    private void clearField(){
        //Done
        this.txtCAdd.setText("");
        this.txtCAdd2.setText("");
        this.txtCName.setText("");
        this.txtCName2.setText("");
        this.txtIC.setText("");
        this.txtIC2.setText("");
        this.txtName.setText("");
        this.txtName2.setText("");
        this.txtSName.setText("");
        this.txtSName2.setText("");
        this.txtSAdd.setText("");
        this.txtSAdd2.setText("");
        this.txtWeight.setText("");
        this.txtWeight2.setText("");
    }
    
    /**
     * Creates new form OrderMgmtjFrame
     */
    public OrderMgmtjFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PackageTypeGroup = new javax.swing.ButtonGroup();
        btnPackage = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnPayment = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        lblCustomerHeader3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblOrderHeader = new javax.swing.JLabel();
        txtOrderNo = new javax.swing.JTextField();
        lblOrderNo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtnNormal = new javax.swing.JRadioButton();
        rbtnPackaga = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        txtIC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSAdd = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCAdd = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblOrderHeader1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rbtnNormal1 = new javax.swing.JRadioButton();
        rbtnPackaga1 = new javax.swing.JRadioButton();
        txtName2 = new javax.swing.JTextField();
        txtIC2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtSName2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSAdd2 = new javax.swing.JTextArea();
        txtWeight2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnSave2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCAdd2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        txtCName2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnSearch2 = new javax.swing.JButton();
        lblOrderList = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtRate2 = new javax.swing.JTextField();
        cBoxOrderNo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        lblIdentity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPackage.setText("Package Management");
        btnPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageActionPerformed(evt);
            }
        });

        btnReport.setText("Report Management");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnPayment.setText("Payment Management");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnDelivery.setText("Delivery Management");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        btnOrder.setText("Order Management");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnCustomer.setText("Customer Management");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        lblCustomerHeader3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblCustomerHeader3.setText("Delivery Management System(DMS)");

        lblOrderHeader.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblOrderHeader.setText("Add New Order");

        txtOrderNo.setEnabled(false);

        lblOrderNo.setText("Order No :");

        jLabel6.setText("Customer Type : ");

        PackageTypeGroup.add(rbtnNormal);
        rbtnNormal.setText("Normal");
        rbtnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNormalActionPerformed(evt);
            }
        });

        PackageTypeGroup.add(rbtnPackaga);
        rbtnPackaga.setSelected(true);
        rbtnPackaga.setText("Package");
        rbtnPackaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPackagaActionPerformed(evt);
            }
        });

        txtName.setEnabled(false);

        jLabel8.setText("IC : ");

        jLabel7.setText("Name : ");

        jLabel9.setText("Shipper Name : ");

        jLabel11.setText("Shipper Address : ");

        txtSAdd.setColumns(20);
        txtSAdd.setRows(5);
        jScrollPane1.setViewportView(txtSAdd);

        txtCAdd.setColumns(20);
        txtCAdd.setRows(5);
        jScrollPane2.setViewportView(txtCAdd);

        jLabel12.setText("Consignee Address : ");

        jLabel10.setText("Consignee Name : ");

        jLabel15.setText("Weight : ");

        jLabel16.setText("kg");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel17.setText("Rate:");

        txtRate.setText("5.0");
        txtRate.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderNo)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearch))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnPackaga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnNormal))))
                            .addComponent(lblOrderHeader)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnSave)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOrderHeader)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderNo)
                    .addComponent(txtOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnPackaga)
                    .addComponent(rbtnNormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnSearch))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(btnSave)))))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Add New Order", jPanel1);

        lblOrderHeader1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblOrderHeader1.setText("Edit Order Record");

        jLabel21.setText("Customer Type : ");

        PackageTypeGroup.add(rbtnNormal1);
        rbtnNormal1.setText("Normal");
        rbtnNormal1.setEnabled(false);
        rbtnNormal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNormal1ActionPerformed(evt);
            }
        });

        PackageTypeGroup.add(rbtnPackaga1);
        rbtnPackaga1.setText("Package");
        rbtnPackaga1.setEnabled(false);
        rbtnPackaga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPackaga1ActionPerformed(evt);
            }
        });

        txtName2.setEnabled(false);

        jLabel22.setText("IC : ");

        jLabel23.setText("Name : ");

        jLabel24.setText("Shipper Name : ");

        jLabel25.setText("Shipper Address : ");

        txtSAdd2.setColumns(20);
        txtSAdd2.setRows(5);
        jScrollPane3.setViewportView(txtSAdd2);

        jLabel26.setText("Weight : ");

        jLabel27.setText("kg");

        btnSave2.setText("Save");
        btnSave2.setEnabled(false);
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        txtCAdd2.setColumns(20);
        txtCAdd2.setRows(5);
        jScrollPane4.setViewportView(txtCAdd2);

        jLabel28.setText("Consignee Address : ");

        jLabel29.setText("Consignee Name : ");

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        lblOrderList.setText("Order No :");

        jLabel18.setText("Rate:");

        txtRate2.setText("5.0");
        txtRate2.setEnabled(false);

        cBoxOrderNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cBoxOrderNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBoxOrderNoItemStateChanged(evt);
            }
        });
        cBoxOrderNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxOrderNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSName2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(txtCName2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnNormal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnPackaga1))
                            .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderList)
                            .addComponent(cBoxOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderHeader1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWeight2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRate2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnSave2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblOrderHeader1)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(rbtnNormal1)
                            .addComponent(rbtnPackaga1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(btnSearch2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblOrderList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtRate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(txtWeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(btnSave2)))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Edit Order Record", jPanel2);

        jLabel4.setText("Welcome !");

        lblIdentity.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPackage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdentity)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCustomerHeader3)
                        .addGap(161, 161, 161)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblIdentity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelivery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPackage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCustomerHeader3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPackageActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        this.setVisible(false);
        new PaymentMgmtJFrame().setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        this.setVisible(false);
        new DeliveryMgmtJFrame().setVisible(true);
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        autoGenerator();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        this.setVisible(false);
        new CustMgmtJFrame().setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void rbtnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNormalActionPerformed
        btnSearch.setVisible(false);
        txtName.setEnabled(true);
    }//GEN-LAST:event_rbtnNormalActionPerformed

    private void rbtnPackagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPackagaActionPerformed
        btnSearch.setVisible(true);
        txtName.setEnabled(false);
    }//GEN-LAST:event_rbtnPackagaActionPerformed

    private void rbtnNormal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNormal1ActionPerformed
        if (this.rbtnNormal.isSelected()==true) {
            this.btnSearch.setVisible(false);
        }
    }//GEN-LAST:event_rbtnNormal1ActionPerformed

    private void rbtnPackaga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPackaga1ActionPerformed
        if (this.rbtnPackaga.isSelected()==true) {
            this.btnSearch.setVisible(true);
        }
    }//GEN-LAST:event_rbtnPackaga1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //Customer Record SEARCH DONE
        boolean recordCheck=false;
        String listCIC;
        custObjs.retrieveData();
        packObj.retrieveData();
        for (int i = 0; i < custObjs.custV.size(); i++) {
             listCIC=Integer.toString(custObjs.custV.elementAt(i).getCustIC());
             if ((this.rbtnPackaga.isSelected()==true) && listCIC.equals(this.txtIC.getText())) {
                this.txtName.setText(custObjs.custV.elementAt(i).getCustName());
                this.txtSName.setText(custObjs.custV.elementAt(i).getShipperName());
                this.txtSAdd.setText(custObjs.custV.elementAt(i).getShipperAdd());
                pno=custObjs.custV.elementAt(i).PackageObj.getPackageNo();
                
                 for (int j = 0; j < packObj.packV.size(); j++) {
                     int pnoList = packObj.packV.elementAt(j).getPackageNo();
                     if(pno== pnoList) {
                        this.txtRate.setText(Double.toString(packObj.packV.elementAt(j).getRate()));
                        recordCheck=true;
                        break;
                     }
                 }
            }
        } 
            if (recordCheck==false) {
                clearField();
                JOptionPane.showMessageDialog(this, "Record Not Found!", "Information",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //NEW ORDER COMPLETE
         try {
            orderNo=Integer.parseInt(this.txtOrderNo.getText());
            IC=Integer.parseInt(this.txtIC.getText());
            weight = Double.parseDouble(this.txtWeight.getText());
            name=this.txtName.getText();
            sName=this.txtSName.getText();
            sAdd=this.txtSAdd.getText();
            cName = this.txtCName.getText();
            cAdd=this.txtCAdd.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Input Format, Field Cannot be Empty", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        amount=((Double.parseDouble(this.txtWeight.getText()))*100) * Double.parseDouble(this.txtRate.getText()) ;
        Order order = new Order(amount,IC,orderNo,weight,name,sName,sAdd,cName,cAdd,"pending");
        orderObj.add(order);
        JOptionPane.showMessageDialog(this, "Order Successful Added!", "Information",JOptionPane.INFORMATION_MESSAGE);
        clearField();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        //SEARCH ORDER COMPLETE
        orderObj.retrieveData();
        boolean recordCheck=false;
        String listCIC,listOno;
        
        for (int i = 0; i < orderObj.orderV.size(); i++) {
             listCIC=Integer.toString(orderObj.orderV.elementAt(i).custObj.getCustIC());
             
             if (listCIC.equals(this.txtIC2.getText())) {
                 for (int j = 1; j < (this.cBoxOrderNo.getItemCount()); j++) { 
                    this.cBoxOrderNo.removeItemAt(1);
                }
                recordCheck=true;
                break;
            }
             else {recordCheck=false;}           
        }
        
        for (int i = 0; i < orderObj.orderV.size(); i++) {
             listCIC=Integer.toString(orderObj.orderV.elementAt(i).custObj.getCustIC());
             if (listCIC.equals(this.txtIC2.getText())) {
                listOno=Integer.toString(orderObj.orderV.elementAt(i).getOrderNo());
                this.cBoxOrderNo.addItem(listOno);
            }
        }
        
        if (recordCheck) {
            this.cBoxOrderNo.removeItemAt(0);
            this.btnSave2.setEnabled(true);
        }
        else {
            clearField();
            this.txtRate2.setText("5.0");
            this.cBoxOrderNo.addItem("-");
                 for (int j = 0; j < (this.cBoxOrderNo.getItemCount()); j++) { 
                    this.cBoxOrderNo.removeItemAt(0); }
            JOptionPane.showMessageDialog(this, "Record Not Found!", "Information",JOptionPane.ERROR_MESSAGE);
            this.btnSave2.setEnabled(false);
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void cBoxOrderNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxOrderNoActionPerformed
       //CHANGE RECORD BASED ON ORDERNO COMPLETE
        String No=this.cBoxOrderNo.getSelectedItem().toString();
        
        if (this.cBoxOrderNo.getSelectedItem()!= "-") {
            for (int i = 0; i <orderObj.orderV.size() ; i++) {
                String tempNo = Integer.toString(orderObj.orderV.elementAt(i).getOrderNo());
                if (tempNo.equals(No)){
                    rate = orderObj.orderV.elementAt(i).getAmount()/(orderObj.orderV.elementAt(i).getWeight()*100);

                    this.txtRate2.setText(Double.toString(Math.round(rate*100.0)/100.0));
                    this.txtCName2.setText(orderObj.orderV.elementAt(i).getCName());
                    this.txtCAdd2.setText(orderObj.orderV.elementAt(i).getCAdd());
                    this.txtName2.setText(orderObj.orderV.elementAt(i).custObj.getCustName());
                    this.txtSName2.setText(orderObj.orderV.elementAt(i).custObj.getShipperName());
                    this.txtSAdd2.setText(orderObj.orderV.elementAt(i).custObj.getShipperAdd());
                    this.txtWeight2.setText(Double.toString(orderObj.orderV.elementAt(i).getWeight()));
                }
            }
        }    
    }//GEN-LAST:event_cBoxOrderNoActionPerformed

    private void cBoxOrderNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBoxOrderNoItemStateChanged
        
    }//GEN-LAST:event_cBoxOrderNoItemStateChanged

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        //SAVE EDITED RECORD COMPLETE 
        try {
            orderNo=Integer.parseInt(this.cBoxOrderNo.getSelectedItem().toString());
            IC=Integer.parseInt(this.txtIC2.getText());
            weight = Double.parseDouble(this.txtWeight2.getText());
            name=this.txtName2.getText();
            sName=this.txtSName2.getText();
            sAdd=this.txtSAdd2.getText();
            cName = this.txtCName2.getText();
            cAdd=this.txtCAdd2.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Input Format, Field Cannot be Empty", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
         
        amount=((Double.parseDouble(this.txtWeight2.getText()))*100) * Double.parseDouble(this.txtRate2.getText()) ;
        Order order = new Order(amount,IC,orderNo,weight,name,sName,sAdd,cName,cAdd,"pending");
        orderObj.edit(order);
        JOptionPane.showMessageDialog(this, "Order Successful Edited!", "Information",JOptionPane.INFORMATION_MESSAGE);
        clearField();
//        this.cBoxOrderNo.removeAllItems();
//        this.cBoxOrderNo.addItem("-");
        
    }//GEN-LAST:event_btnSave2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderMgmtjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderMgmtjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderMgmtjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderMgmtjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderMgmtjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup PackageTypeGroup;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPackage;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JComboBox cBoxOrderNo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCustomerHeader3;
    public static javax.swing.JLabel lblIdentity;
    private javax.swing.JLabel lblOrderHeader;
    private javax.swing.JLabel lblOrderHeader1;
    private javax.swing.JLabel lblOrderList;
    private javax.swing.JLabel lblOrderNo;
    private javax.swing.JRadioButton rbtnNormal;
    private javax.swing.JRadioButton rbtnNormal1;
    private javax.swing.JRadioButton rbtnPackaga;
    private javax.swing.JRadioButton rbtnPackaga1;
    private javax.swing.JTextArea txtCAdd;
    private javax.swing.JTextArea txtCAdd2;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCName2;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtIC2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtOrderNo;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtRate2;
    private javax.swing.JTextArea txtSAdd;
    private javax.swing.JTextArea txtSAdd2;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSName2;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtWeight2;
    // End of variables declaration//GEN-END:variables
}
